# DO NOT EDIT THIS FILE
#
# Please edit /boot/dietpiEnv.txt to set supported parameters
#
# If you must, edit /boot/boot.cmd and recompile /boot/boot.scr with:
# mkimage -C none -A arm64 -T script -d /boot/boot.cmd /boot/boot.scr
#
# TVBox S90X: These boxes boot via the vendor firmware and a chain-loaded Armbian multiboot
# U-Boot (u-boot.ext). That U-Boot reads this script as /boot/boot.scr, but does not set
# all environment defaults this script relies on, hence they are defined explicitly below.
# The script detects whether it was loaded from SD, eMMC or USB and loads all files from
# the same partition, which allows running the image from SD card and intern eMMC alike.

# Default environment
setenv rootdev "/dev/mmcblk0p2"
setenv rootfstype "ext4"
setenv consoleargs "console=tty1"

# Load addresses
setenv scriptaddr "0x32000000"
setenv kernel_addr_r "0x34000000"
setenv ramdisk_addr_r "0x12000000"
setenv fdt_addr_r "0x4080000"

# Boot device detection: use the partition this script was loaded from
if test -e mmc 0:1 boot.scr; then
	setenv devtype "mmc"
	setenv devnum "0:1"
elif test -e mmc 1:1 boot.scr; then
	setenv devtype "mmc"
	setenv devnum "1:1"
elif test -e usb 0:1 boot.scr; then
	setenv devtype "usb"
	setenv devnum "0:1"
else
	setenv devtype "mmc"
	setenv devnum "0:1"
fi
setenv prefix ""

# If this script was loaded from SD/eMMC, get PARTUUID of its boot partition for later detection from userland
if test "${devtype}" = "mmc"; then part uuid mmc "${devnum}" ubootpart; fi

# Default device tree, overridden by dietpiEnv.txt if existent
setenv fdtfile "amlogic/meson-gxl-s905x-p212.dtb"

# Load environment file
if load "${devtype}" "${devnum}" "${scriptaddr}" "${prefix}dietpiEnv.txt"; then
	env import -t "${scriptaddr}" "${filesize}"
fi

# Define kernel command-line arguments
setenv bootargs "root=${rootdev} rootfstype=${rootfstype} rootwait ${consoleargs} coherent_pool=2M ubootpart=${ubootpart} ${extraargs}"

# Load device tree and apply overlays
load "${devtype}" "${devnum}" "${fdt_addr_r}" "${prefix}dtb/${fdtfile}"
fdt addr "${fdt_addr_r}"
if test -n "${overlays}${user_overlays}"; then
	setenv overlay_error "false"
	fdt resize 65536
	for overlay in ${overlays}; do
		for pre in ${overlay_prefix}; do
			if test -e  "${devtype}" "${devnum}" "${prefix}dtb/${overlay_path}/overlay/${pre}-${overlay}.dtbo"; then
				if load "${devtype}" "${devnum}" "${scriptaddr}" "${prefix}dtb/${overlay_path}/overlay/${pre}-${overlay}.dtbo"; then
					echo "Applying kernel provided DT overlay ${pre}-${overlay}.dtbo"
					if fdt apply "${scriptaddr}"; then
						if test -e "${devtype}" "${devnum}" "${prefix}dtb/${overlay_path}/overlay/${pre}-${overlay}.scr"; then
							if load "${devtype}" "${devnum}" "${scriptaddr}" "${prefix}dtb/${overlay_path}/overlay/${pre}-${overlay}.scr"; then
								echo "Applying kernel provided DT overlay fixup script ${pre}-${overlay}.scr"
								source "${scriptaddr}" || setenv overlay_error "true"
							fi
						fi
					else
						setenv overlay_error "true"
					fi
				fi
				break
			fi
		done
	done

	for overlay in ${user_overlays}; do
		if load "${devtype}" "${devnum}" "${scriptaddr}" "${prefix}overlay-user/${overlay}.dtbo"; then
			echo "Applying user provided DT overlay ${overlay}.dtbo"
			fdt apply "${scriptaddr}" || setenv overlay_error "true"
		fi
	done

	if test "${overlay_error}" = "true"; then
		echo "Error applying DT overlays, restoring original DT"
		load "${devtype}" "${devnum}" "${fdt_addr_r}" "${prefix}dtb/${fdtfile}"
	fi
fi

# Load kernel and initramfs last, for U-Boot to set ${filesize}, needed to load raw initrd
load "${devtype}" "${devnum}" "${kernel_addr_r}" "${prefix}Image"
load "${devtype}" "${devnum}" "${ramdisk_addr_r}" "${prefix}initrd.img"

# Boot
booti "${kernel_addr_r}" "${ramdisk_addr_r}:${filesize}" "${fdt_addr_r}"